#!/bin/sh

/usr/bin/clear
echo "Current directory:" `pwd`
echo "Current host     :" `hostname`
echo ""

if [ -f AMaLGaM-FOS ]
then
  rm AMaLGaM-FOS
fi

echo -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
gcc -lm -g -w -pipe -Wall -W -DNO_DEBUG -o AMaLGaM-FOS AMaLGaM-FOS.c
echo -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

if [ -f AMaLGaM-FOS.exe ]
then
  mv AMaLGaM-FOS.exe AMaLGaM-FOS
fi
